version: '3.9'
services:
  db:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  DBMS:
    image: adminer:latest
    restart: always
    ports:
      - "8081:8080"
    depends_on:
      - db

#  app:
#    build: .
#    restart: always
#    ports:
#      - "8080:8080"
#    depends_on:
#      - database
#    environment:
#      - SPRING_DATASOURCE_URL=jdbc:postgresql://database:5432/postgres
#      - SPRING_DATASOURCE_USERNAME=postgres
#      - SPRING_DATASOURCE_PASSWORD=password
#      - SPRING_JPA_HIBERNATE_DDL_AUTO=update



